using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Webbpay.Api.PaymentService.Entities.Razer
{
    public class RazerRefundRequest
    {
        /// <summary>
        /// P - Partial,
        /// F - Full
        /// </summary>
        public string RefundType { get; set; }

        public string MerchantID { get; set; }

        /// <summary>
        /// Generated by system
        /// </summary>
        public string RefID { get; set; }

        public string TxnID { get; set; }

        public decimal Amount { get; set; }

        public string Signature { get; set; }

    }
}
