// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webbpay.Api.PaymentService.Adapters.Database;

namespace Webbpay.Api.PaymentService.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20210522045348_Update PaymentTransaction table")]
    partial class UpdatePaymentTransactiontable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentGatewayConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("GatewayType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentGatewayConfig");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentGatewayConfigSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("PaymentGatewayConfigSettings");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentGatewayConfigValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConfigType")
                        .HasColumnType("longtext");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PaymentGatewayConfigId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentGatewayConfigId");

                    b.ToTable("PaymentGatewayConfigValue");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaymentLinkRef")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id", "StoreId");

                    b.ToTable("PaymentLink");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactMobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactName")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPostcode")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactState")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PaymentLinkId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PaymentLinkStoreId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<string>("PaymentRefNo")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentRemarks")
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentLinkId", "PaymentLinkStoreId");

                    b.ToTable("PaymentTransaction");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentGatewayConfigValue", b =>
                {
                    b.HasOne("Webbpay.Api.PaymentService.Entities.PaymentGatewayConfig", null)
                        .WithMany("PaymentGatewayValues")
                        .HasForeignKey("PaymentGatewayConfigId");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Webbpay.Api.PaymentService.Entities.PaymentLink", null)
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PaymentLinkId", "PaymentLinkStoreId");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentGatewayConfig", b =>
                {
                    b.Navigation("PaymentGatewayValues");
                });

            modelBuilder.Entity("Webbpay.Api.PaymentService.Entities.PaymentLink", b =>
                {
                    b.Navigation("PaymentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
